# Generated by Django 2.2.8 on 2019-12-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(1, 'Motoryzacja'), (2, 'Elektronika'), (3, 'Usługi'), (4, 'Sport'), (5, 'Inne')], default=1),
        ),
    ]
